/* ParserTokenManager.java */
/* Generated by: ParserGeneratorCC: Do not edit this line. ParserTokenManager.java */
package ru.vsu.cs.course4.compiler;
import java.util.*;
import ru.vsu.cs.course4.compiler.ast.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class ParserTokenManager implements ParserConstants {
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x20000000L) != 0x0L)
            return 18;
         if ((active0 & 0x7f800L) != 0x0L)
         {
            jjmatchedKind = 19;
            return 16;
         }
         return -1;
      case 1:
         if ((active0 & 0x7f000L) != 0x0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 1;
            return 16;
         }
         if ((active0 & 0x800L) != 0x0L)
            return 16;
         return -1;
      case 2:
         if ((active0 & 0x73000L) != 0x0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 2;
            return 16;
         }
         if ((active0 & 0xc000L) != 0x0L)
            return 16;
         return -1;
      case 3:
         if ((active0 & 0x11000L) != 0x0L)
            return 16;
         if ((active0 & 0x62000L) != 0x0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 3;
            return 16;
         }
         return -1;
      case 4:
         if ((active0 & 0x22000L) != 0x0L)
            return 16;
         if ((active0 & 0x40000L) != 0x0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 4;
            return 16;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case '!':
         jjmatchedKind = 34;
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case '%':
         return jjStopAtPos(0, 30);
      case '&':
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case '(':
         return jjStopAtPos(0, 22);
      case ')':
         return jjStopAtPos(0, 23);
      case '*':
         return jjStopAtPos(0, 28);
      case '+':
         jjmatchedKind = 26;
         return jjMoveStringLiteralDfa1_0(0x800000000L);
      case ',':
         return jjStopAtPos(0, 20);
      case '-':
         jjmatchedKind = 27;
         return jjMoveStringLiteralDfa1_0(0x1000000000L);
      case '/':
         return jjStartNfaWithStates_0(0, 29, 18);
      case ';':
         return jjStopAtPos(0, 21);
      case '<':
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case '=':
         jjmatchedKind = 31;
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case '>':
         jjmatchedKind = 41;
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case '[':
         return jjStopAtPos(0, 32);
      case ']':
         return jjStopAtPos(0, 33);
      case 'd':
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 'e':
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 'f':
         return jjMoveStringLiteralDfa1_0(0x24000L);
      case 'i':
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 'r':
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 't':
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 'w':
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case '{':
         return jjStopAtPos(0, 24);
      case '|':
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case '}':
         return jjStopAtPos(0, 25);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case '&':
         if ((active0 & 0x80000000000L) != 0x0L)
            return jjStopAtPos(1, 43);
         break;
      case '+':
         if ((active0 & 0x800000000L) != 0x0L)
            return jjStopAtPos(1, 35);
         break;
      case '-':
         if ((active0 & 0x1000000000L) != 0x0L)
            return jjStopAtPos(1, 36);
         break;
      case '=':
         if ((active0 & 0x2000000000L) != 0x0L)
            return jjStopAtPos(1, 37);
         else if ((active0 & 0x4000000000L) != 0x0L)
            return jjStopAtPos(1, 38);
         else if ((active0 & 0x10000000000L) != 0x0L)
            return jjStopAtPos(1, 40);
         else if ((active0 & 0x40000000000L) != 0x0L)
            return jjStopAtPos(1, 42);
         break;
      case 'a':
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 'e':
         return jjMoveStringLiteralDfa2_0(active0, 0x48000L);
      case 'f':
         if ((active0 & 0x800L) != 0x0L)
            return jjStartNfaWithStates_0(1, 11, 16);
         break;
      case 'h':
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 'l':
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 'o':
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 'r':
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case '|':
         if ((active0 & 0x100000000000L) != 0x0L)
            return jjStopAtPos(1, 44);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 'f':
         if ((active0 & 0x8000L) != 0x0L)
            return jjStartNfaWithStates_0(2, 15, 16);
         break;
      case 'i':
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 'l':
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 'r':
         if ((active0 & 0x4000L) != 0x0L)
            return jjStartNfaWithStates_0(2, 14, 16);
         break;
      case 's':
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 't':
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
      case 'u':
         return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 'e':
         if ((active0 & 0x1000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 12, 16);
         else if ((active0 & 0x10000L) != 0x0L)
            return jjStartNfaWithStates_0(3, 16, 16);
         break;
      case 'l':
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 's':
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
      case 'u':
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 'e':
         if ((active0 & 0x2000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 13, 16);
         else if ((active0 & 0x20000L) != 0x0L)
            return jjStartNfaWithStates_0(4, 17, 16);
         break;
      case 'r':
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 'n':
         if ((active0 & 0x40000L) != 0x0L)
            return jjStartNfaWithStates_0(5, 18, 16);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec1 = {
   0xffffffffffff0000L, 0xffffL, 0x0L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 32;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0x0L)
                  {
                     if (kind > 6)
                        kind = 6;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if ((0x100002600L & l) != 0x0L)
                  {
                     if (kind > 1)
                        kind = 1;
                  }
                  else if (curChar == 47)
                     { jjAddStates(3, 4); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(5, 7); }
                  else if (curChar == 39)
                     { jjAddStates(8, 9); }
                  else if (curChar == 46)
                     { jjCheckNAdd(4); }
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 18:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(24, 26); }
                  else if (curChar == 47)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 1:
                  if (curChar == 10 && kind > 1)
                     kind = 1;
                  break;
               case 2:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 46)
                     { jjCheckNAdd(4); }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjCheckNAdd(4); }
                  break;
               case 5:
                  if (curChar == 39)
                     { jjAddStates(8, 9); }
                  break;
               case 6:
                  if ((0xffffff7fffffffffL & l) != 0x0L)
                     { jjCheckNAdd(7); }
                  break;
               case 7:
                  if (curChar == 39 && kind > 9)
                     kind = 9;
                  break;
               case 9:
                  if ((0x8400000000L & l) != 0x0L)
                     { jjCheckNAdd(7); }
                  break;
               case 10:
                  if (curChar == 34)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 11:
                  if ((0xfffffffbffffffffL & l) != 0x0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 13:
                  if ((0x8400000000L & l) != 0x0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 14:
                  if (curChar == 34 && kind > 10)
                     kind = 10;
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 17:
                  if (curChar == 47)
                     { jjAddStates(3, 4); }
                  break;
               case 19:
                  if ((0xffffffffffffdbffL & l) != 0x0L)
                     { jjCheckNAddStates(10, 12); }
                  break;
               case 20:
                  if ((0x2400L & l) != 0x0L && kind > 2)
                     kind = 2;
                  break;
               case 21:
                  if (curChar == 10 && kind > 2)
                     kind = 2;
                  break;
               case 22:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(24, 26); }
                  break;
               case 24:
                  if ((0xffff7fffffffffffL & l) != 0x0L)
                     { jjCheckNAddTwoStates(24, 26); }
                  break;
               case 25:
                  if (curChar == 47 && kind > 3)
                     kind = 3;
                  break;
               case 26:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(28); }
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(29, 30); }
                  break;
               case 30:
                  if (curChar != 46)
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjCheckNAdd(31); }
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjCheckNAdd(31); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 16:
                  if ((0x7fffffe87fffffeL & l) == 0x0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  { jjCheckNAdd(16); }
                  break;
               case 6:
                  if ((0xffffffffefffffffL & l) != 0x0L)
                     { jjCheckNAdd(7); }
                  break;
               case 8:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0x14404410000000L & l) != 0x0L)
                     { jjCheckNAdd(7); }
                  break;
               case 11:
                  if ((0xffffffffefffffffL & l) != 0x0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 12:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x14404410000000L & l) != 0x0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 19:
                  { jjAddStates(10, 12); }
                  break;
               case 24:
                  { jjAddStates(13, 14); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 16:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 19)
                     kind = 19;
                  { jjCheckNAdd(16); }
                  break;
               case 6:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 11:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(5, 7); }
                  break;
               case 19:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(10, 12); }
                  break;
               case 24:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(13, 14); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      i = jjnewStateCnt;
      jjnewStateCnt = startsAt;
      startsAt = 32 - jjnewStateCnt;
      if (i == startsAt)
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, "\151\146", 
"\145\154\163\145", "\167\150\151\154\145", "\146\157\162", "\144\145\146", "\164\162\165\145", 
"\146\141\154\163\145", "\162\145\164\165\162\156", null, "\54", "\73", "\50", "\51", "\173", "\175", 
"\53", "\55", "\52", "\57", "\45", "\75", "\133", "\135", "\41", "\53\53", "\55\55", 
"\75\75", "\41\75", "\74", "\74\75", "\76", "\76\75", "\46\46", "\174\174", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = im == null ? input_stream.getImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   28, 29, 30, 18, 23, 11, 12, 14, 6, 8, 19, 20, 22, 24, 26, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 4:
         return ((jjbitVec1[i2] & l2) != 0L);
      default :
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop:
  for (;;)
  {
   try
   {
      curChar = input_stream.beginToken();
   }
   catch(final Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try {
     input_stream.readChar();
     input_stream.backup(1);
   }
   catch (final java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.getImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.getImage();
   }
   throw new TokenMgrException(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrException.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParserTokenManager(SimpleCharStream stream){
    input_stream = stream;
  }

  /** Constructor. */
  public ParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 32; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrException("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrException.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x1ffffffffec1L, 
};
static final long[] jjtoSkip = {
   0xeL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[32];
    private final int[] jjstateSet = new int[2 * 32];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
